name: Booker Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Verify build output
      run: |
          ls -la
          ls -la dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:

      - name: Deploy
        uses: nwtgck/actions-netlify@v3.0

        with:
            publish-dir: './public'
            production-branch: main
            deploy-message: "Deploy from GitHub Actions"
            enable-pull-request-comment: false
            enable-commit-comment: true
            overwrites-pull-request-comment: true
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
