name: Booker Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print build directory
      run: |
        pwd
        ls -la
        npm run build
        ls -la

    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: List build directory contents
        run: ls -la

      - name: Deploy
        uses: nwtgck/actions-netlify@v3.0

        with:
            publish-dir: './dist'
            production-branch: main
            deploy-message: "Deploy from GitHub Actions"
            enable-pull-request-comment: false
            enable-commit-comment: true
            overwrites-pull-request-comment: true
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            timeout-minutes: 1
